### ISSUE TITLE
Why not using $SNAP_COMMON and $SNAP_DATA as home/config paths?

### ISSUE THREAD

**Issue by 3v1n0** [GitHubForSnap/syncthing-gael#2]
Given that this snap is a daemon and so ran as root, why not just using the default folders instead of saving stuff under /root?

**Comment by GitHubForSnap** [comment]
Hi Marco,

You are right, I should have.
This was my 1st snap and, at the time, I didn't fully understand the difference between $SNAP_COMMON/$SNAP_USER_COMMON and $SNAP_DATA/$SNAP_USER_DATA.

Changing this now would be great for new installs but risky for users upgrading, don't you think?
I need to test and see how syncthing will react (and do some serious non-regression tests).

Cheers,
Gaël

**Comment by 3v1n0** [comment]
Well, for upgraders shouldn't be a big deal even, given that the conf files don't have references to their absolute path.

As they only reference shared folders... In fact I've moved my old config that was in ~/snap/syncthing to /root/snap/syncthing-gael with no problems.

However, indeed would probably make sense to have testing... I assume that using github actions, something could be simulated...
