### ISSUE TITLE
Files are stored in /var/snap/syncthing-gael/ instead of the user's home folder

### ISSUE THREAD

**Issue by vincenttschanz** [GitHubForSnap/syncthing-gael#3]
Ubuntu 24.10 adm64, syncthing 1.28.0

When creating a new share, the webui indicate `~/` as base folder. Usually this is the home folder of the user. Here instead it's /`var/snap/syncthing-gael/ `.

Is this on purpose? (snap limitation?)

**Comment by GitHubForSnap** [comment]
Hi,

This version of syncthing as a snap is designed for IoT and servers (where it makes sense to use /var/snap/syncthing-gael/common).
Specifically for Ubuntu Core where DEB packages are not an option.

If you are looking for a desktop-version snap, the other syncthing snap would better suit your needs (https://snapcraft.io/syncthing-arubislander).
Unfortunately, their package is not always as up-to-date as it should be.

But, in my opinion, if you want to use syncthing on a desktop, there is no better option than the official DEB package.
It is updated the minute a new version is available and the syncthing Team will provide support if need be.
Documentation is here https://apt.syncthing.net/

I will update the description to avoid any confusion.

Thanks for raising this issue.

**Comment by GitHubForSnap** [comment]
Description has been updated on GitHub.com (commit 0caa7d02260249bfc199fdfe843a8776e3fec3e0) and Snapcraft.io.

Thanks.
